Prepare for a stable release
zendframework/zend-expressive-authentication-session pull request #19
Opened 2018-09-26 22:00 UTC by weierophinney

This patch accomplishes two things:

- It updates the zend-expressive-authentication requirement to `^1.0`. All tests continue to pass as-is.
- It fleshes out the documentation to detail how to configure the package, add a login handler, and add authentication to an existing application (as it requires both the session and authentication middleware).

Fixes #17
Supercedes #18

2018-09-26 22:01 UTC, weierophinney commented
@ezimuel Could you review the documentation to make sure it's correct? I wrote a demo application, but did not have a user repository to test against and validate the approach.

2018-09-27 09:52 UTC, jonsa commented
@weierophinney As far as I can tell this won't work as is. The `UserInterface::getRoles()` method now returns an `iterable` which includes `Generators`, which my pull request tried to handle.

Some nitpicking: The form example in the documentation should include the name attribute on the fields otherwise nothing is posted.

2018-09-27 10:28 UTC, froschdesign requested changes
Only litte changes necessary.

I like the example with the login handler. 👍

2018-09-27 10:28 UTC, froschdesign commented on mkdocs.yml
> +copyright: 'Copyright (c) 2017-2018 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
Can be removed, because this line is no longer used by the documentation theme.

2018-09-27 10:28 UTC, froschdesign commented on docs/book/v1/login-handler.md
> +    $app->get(
The indention is not needed for this example.

2018-09-27 10:28 UTC, froschdesign commented on docs/book/v1/login-handler.md
> +                <input type="text" class="form-control" id="username" placeholder="Enter username">
`name` attribute is missing.

2018-09-27 10:28 UTC, froschdesign commented on docs/book/v1/login-handler.md
> +                <input type="password" class="form-control" id="password" placeholder="Password">
`name` attribute is missing.

2018-09-27 10:28 UTC, froschdesign commented on docs/book/v1/config.md
> +<?php
If the code example does not present template code, this line should be omitted.

2018-09-27 10:28 UTC, froschdesign commented on mkdocs.yml
>      - index.md
Can you add "Home" (`- Home: index.md`) here? I think, then the entry in the subnavigation is skipped.

2018-09-27 10:56 UTC, jonsa commented
I played around with the documentation example a little bit more and I cannot get it to work. Unless I'm missing something obvious I have to enable POST on all my routes since the LoginHandler set the form action to be that of `$redirect`. So when I send the login form I get a 405 (Method not allowed) when I successfully login.

2018-09-27 13:15 UTC, weierophinney commented
> As far as I can tell this won't work as is. The `UserInterface::getRoles()` method now returns an `iterable` which includes `Generators`. In my pull request I tried to handle that.

When the tests passed as-is, I missed this. But you're right - when we serialize the session, we need to grab all of them. I'll merge your patch into my branch so we get that functionality in place.

2018-09-27 13:16 UTC, weierophinney commented
> I played around with the documentation example a little bit more and I cannot get it to work. Unless I'm missing something obvious I have to enable POST on all my routes since the LoginHandler set the form action to be that of `$redirect`. So when I send the login form I get a 405 (Method not allowed) when I successfully login.

I had a nagging suspicion that may be the case. I'll post some updates shortly to see if I can resolve this via the `LoginHandler`.

2018-09-27 13:49 UTC, weierophinney commented
@jonsa I've rewritten the page covering the login handler. Can you review and test to ensure it works as expected, please?

2018-09-27 13:49 UTC, weierophinney commented
@froschdesign I've incorporated all feedback you presented at this time.

2018-09-27 15:30 UTC, jonsa commented
@weierophinney Your solution looks more or less the same as what I've come up with so far. It has one problem though. When submitting the login form with invalid credentials `AuthenticationMiddleware` will redirect to the login page and you loose any knowledge that a sign in has occurred and cannot give the user any feedback.

2018-09-27 15:38 UTC, weierophinney commented
> It has one problem though. When submitting the login form with invalid credentials `AuthenticationMiddleware` will redirect to the login page and you loose any knowledge that a sign in has occurred and cannot give the user any feedback.

This is due to how the adapter works, as the `unauthenticatedResponse()` method performs a redirect.

The only way we could handle that differently is to have middleware intercepting before the `AuthenticationMiddleware` that uses something like zend-expressive-flash to store the previous values and/or a message indicating invalid credentials when it detects a 401 response to the login page... and, frankly, that seems far too complicated.

Alternately, I could modify the `LoginHandler` to also accept the `PhpSession` adapter and perform the authentication attempt itself; that would allow it to re-display the login form for an invalid attempt.

That might actually be a better approach in the end. I'm going to create a patch that does this, and will ping you when it's pushed.

2018-09-27 16:19 UTC, jonsa commented
My solution at the moment works the other way around. I'm wrapping `PhpSession` with a "smarter" adapter that takes the `LoginHandler` as an argument and internally takes care of handling the store previous url and redirect back on successful login. This makes defining the `/login` route redundant.

The gist of it is that I return `null` in `authenticate` if I'm on the configured login path and redirects back in `unauthorizedResponse` if the session contains `UserInterface`.

2018-09-27 16:35 UTC, weierophinney commented
@jonsa I've updated the docs and pushed just now. We can also provide your approach as an alternative if you'd like; they're both valid, and it might be interesting to demonstrate each.

2018-09-27 19:24 UTC, merged

2018-09-27 19:24 UTC, weierophinney commented
@jonsa Definitely send in a PR detailing your approach; we can merge that at any time, and it will immediately publish to the documentation.

2019-01-15 23:22 UTC, icetee commented
I think it is useful information to overwrite the default `username` field, for example `email`. I had to look at the code all the way, to understand.

```
'username' => null, // provide a custom field name for the username
'password' => null, // provide a custom field name for the password
```


PS: Otherwise more beautiful property name `identity` and default `username`. See `PdoDatabase`.

2019-01-15 23:24 UTC, weierophinney commented
@icetee Please don't comment on an already merged request. Add a feature request or pull request, but don't comment on something already complete.